# Generated by Django 3.0.5 on 2021-10-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(max_length=50, verbose_name='Contact name')),
                ('contactData', models.CharField(max_length=50, verbose_name='Contact data')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100, verbose_name='Course Name')),
                ('courseDateFrom', models.CharField(blank=True, max_length=10)),
                ('courseDateTo', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historyPosition', models.CharField(max_length=50, verbose_name='History Position')),
                ('historyFirm', models.CharField(max_length=50, verbose_name='History Firm')),
                ('historyDateFrom', models.CharField(blank=True, max_length=10)),
                ('historyDateTo', models.CharField(blank=True, max_length=10)),
                ('historyDescription', models.TextField(max_length=500, verbose_name='History Description')),
                ('historySkills', models.CharField(max_length=100, verbose_name='History Skills')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myFirstName', models.CharField(max_length=50, verbose_name='First Name')),
                ('myLastName', models.CharField(max_length=50, verbose_name='Last Name')),
                ('myPic', models.ImageField(upload_to='myportfolio/media', verbose_name='Image')),
                ('myProfession', models.CharField(max_length=50, verbose_name='Profession')),
                ('myDescription', models.TextField(max_length=500, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolioName', models.CharField(max_length=50, verbose_name='Portfolio Name')),
                ('portfolioType', models.CharField(max_length=50, verbose_name='Portfolio Type')),
                ('portfolioMedia', models.ImageField(upload_to='myportfolio/media')),
                ('portfolioURL', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillType', models.CharField(max_length=20, verbose_name='Skill type')),
                ('skillBar', models.IntegerField(blank=True)),
            ],
        ),
    ]
